let films = [{
        'img': 'img/posters/bloodshot.jpeg',
        'name': 'Бладшот',
        'year': '2019',
        'country': 'США',
        'genre': 'Боевик',
        'director': 'Дейв Уилсон',
    },
    {
        'img': 'img/posters/joker.jpeg',
        'name': 'Джокер',
        'year': '2019',
        'country': 'США',
        'genre': 'Драма',
        'director': 'Тодд Филлипс',
    },
    {
        'img': 'img/posters/casino.jpeg',
        'name': 'Казино',
        'year': '1995',
        'country': 'США',
        'genre': 'Драма',
        'director': 'Мартин Скорсезе',
    },
    {
        'img': 'img/posters/boy.jpeg',
        'name': 'Кукла-2',
        'year': '2020',
        'country': 'Нидерланды',
        'genre': 'Ужасы',
        'director': 'Уильям Брент Белл',
    },
    {
        'img': 'img/posters/primal.jpeg',
        'name': 'Звериная ярость',
        'year': '2019',
        'country': 'США',
        'genre': 'Боевик',
        'director': 'Ник Пауэлл',

    },
    {
        'img': 'img/posters/aviator.jpeg',
        'name': 'Авиатор',
        'year': '2004',
        'country': 'США',
        'genre': 'Исторический',
        'director': 'Мартин Скорсезе',

    },
    {
        'img': 'img/posters/unnamed.jpeg',
        'name': 'Непрощенный',
        'year': '1992',
        'country': 'США',
        'genre': 'Вестерн',
        'director': 'Клинт Иствуд',
    },
    {
        'img': 'img/posters/Wasabi-1.jpeg',
        'name': 'Васаби',
        'year': '2001',
        'country': 'Франция',
        'genre': 'Комедия',
        'director': 'Жерар Кравчик',
    },
    {
        'img': 'img/posters/Taxi-4.jpeg',
        'name': 'Такси-4',
        'year': '2007',
        'country': 'Франция',
        'genre': 'Комедия',
        'director': 'Жерар Кравчик',
    },
    {
        'img': 'img/posters/Unforgiven.jpeg',
        'name': 'Непрощенный',
        'year': '2018',
        'country': 'Россия',
        'genre': 'Драма',
        'director': 'Сарик Андреасян',
    },
    {
        'img': 'img/posters/Konvert.jpeg',
        'name': 'Конверт',
        'year': '2017',
        'country': 'Россия',
        'genre': 'Ужасы',
        'director': 'Владимир Марков',
    },
    {
        'img': 'img/posters/Country-03.jpeg',
        'name': 'Страна 03',
        'year': '2015',
        'country': 'Россия',
        'genre': 'Комедия',
        'director': 'Василий Сигарев',
    }
];

// localStorage.setItem('films', JSON.stringify(films))